apps/productos/urls.py
from django.urls    import path
from .              import views

app_name = "productos"

urlpatterns = [
    path('detalle/', views.detalle, name="detalle"),

    #Admin
    path('admin/listar/', views.ListarAdmin.as_view(), name="admin_listar"),
    path('admin/nuevo/', views.NuevoAdmin.as_view(), name="admin_nuevo"),
    path('admin/editar/<int:pk>/', views.EditarAdmin.as_view(), name="admin_editar"),
    path('admin/eliminar/<int:pk>/', views.EliminarAdmin.as_view(), name="admin_eliminar"),
]

nombre_proyecto/urls.py
from django.contrib         import admin
from django.contrib.auth    import views as auth_views
from django.urls            import path, include
from . import views 

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    #path('inicio/', views.inicio, name="inicio"),
    path('', views.Inicio.as_view(), name="inicio"),
    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', auth_views.logout_then_login, name="logout"),
    #Includes
    path('productos/', include('apps.productos.urls'))
]

apps/productos/models.py
from django.db import models

class Producto(models.Model):
    nombre = models.CharField(max_length=255)
    precio = models.DecimalField(max_digits=9, decimal_places=2)

    class Meta:
        db_table="productos"

    def __str__(self):
        return self.nombre #devuelvo el nombre del producto

apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    dni = models.IntegerField(null=True, blank=True)
    #foto = models.ImageField()

    class Meta:
        db_table="usuarios"

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

apps/productos/forms.py
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):
    nombre = forms.CharField(label="Nombre del productos", widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Por favor ingrese el nombre del producto"}))
    class Meta:
        model = Producto
        fields = ["nombre", "precio"]

apps/productos/views.py
from django.shortcuts import render
from apps.productos.models import Producto
from django.views.generic import ListView, CreateView
from django.views.generic.edit import UpdateView, DeleteView
from .forms import ProductoForm
from django.urls import reverse_lazy

def detalle(request):
    contex = {}
    return render(request, "productos/detalle.html", contex)

class ListarAdmin(ListView):
    template_name="productos/admin/listar.html"
    model = Producto
    context_object_name="productos"

    def get_queryset(self):
         self.request
         return Producto.objects.all().order_by("nombre")
    
class NuevoAdmin(CreateView):
    template_name = "productos/admin/nuevo.html"
    model = Producto
    form_class = ProductoForm

    def get_success_url(self, **kwargs):
        return reverse_lazy("productos:admin_listar")


class EditarAdmin(UpdateView):
    template_name = "productos/admin/editar.html"
    model = Producto
    form_class = ProductoForm

    def get_success_url(self, **kwargs):
        return reverse_lazy("productos:admin_listar")

class EliminarAdmin(DeleteView):
    model = Producto
    success_url = reverse_lazy("productos:admin_listar")
    

apps/usuarios/views.py
from django.shortcuts import render

# Create your views here.

nombre_proyecto/views.py
# from django.shortcuts import render
from apps.productos.models import Producto
from django.views.generic.base import TemplateView


"""
# Inicio basado en función
def inicio(request):
    contex = {
        "productos": Producto.objects.all()
    }
    return render(request, "inicio.html", contex) 
"""

class Inicio(TemplateView):
    template_name = "inicio.html"

    def get_context_data(self, **kwargs):
        context = super(Inicio, self).get_context_data(**kwargs)
        context["productos"] = Producto.objects.all()
        return context
    

templates/base/base.html
<!DOCTYPE html>
<html lang="es" data-lt-installed="true">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Hugo 0.88.1">
        <title>InforMarket - Informatorio 2021</title>
        <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/album/">
        <!-- CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <meta name="theme-color" content="#7952b3">
        <style>
            .bd-placeholder-img {
                font-size: 1.125rem;
                text-anchor: middle;
                -webkit-user-select: none;
                -moz-user-select: none;
                user-select: none;
            }
            @media (min-width: 768px) {
                .bd-placeholder-img-lg {
                font-size: 3.5rem;
                }
            }
        </style>
    </head>
    <body>
        <header>
            {% include "base/header.html" %}
        </header> 
        <main>
            <section class="py-5 text-center container">
                {% include "base/portada.html" %}
            </section>
            <div class="album py-5 bg-light">
                <div class="container">
                    <ul class="nav nav-pills">
                        <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="#">MENU</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'inicio' %}">Inicio</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#">Catalogo</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'productos:admin_listar' %}">Productos</a>
                        </li>
                      </ul>
                    {% block contenido %}
                    
                    {% endblock contenido %}
                </div>
            </div>
        </main>

        <footer class="text-muted py-5">
            {% include "base/footer.html" %}
        </footer>
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
</html>

templates/base/footer.html
<div class="container">
    <p class="float-end mb-1">
        <a href="#">Ir al inicio</a>
    </p>
    <p class="mb-1">Sitio web con objetivos de aprendizaje. Framework Django. Informatorio 2021.</p>
    <!-- <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.1/getting-started/introduction/">getting started guide</a>.</p> -->
</div>

templates/base/header.html
<div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
                <h4 class="text-white">Sobre Nosotros</h4>
                <p class="text-muted">Este sitio fue desarrollado en el Informatorio - Comisión 4. Estamos aprendiendo Django.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}" class="text-white">Cerrar sesión</a></li>
                    {% else %}    
                        <li><a href="{% url 'login' %}" class="text-white">Iniciar sesión</a></li>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
        <a href="{% url 'inicio' %}" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>InforMarket</strong>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</div>

templates/base/portada.html
<div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Bienvenido al comercio del Info</h1>
        <p class="lead text-muted">Estamos desarrollando un sitio de comercio electronico en la com. 4.</p>
        <!--
        <p>
        <a href="#" class="btn btn-primary my-2">Boton 1</a>
        <a href="#" class="btn btn-secondary my-2">Boton 2</a>
        </p>
        -->
    </div>
</div>

templates/includes/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>{{field.label}}</strong> {{error}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errrors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{error}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}

templates/inicio.html
{% extends 'base/base.html' %}

    {% block contenido %}
        <h2>Ofertas del día</h2>
                    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                        {% for i in productos %}
                        <div class="col">
                            <div class="card shadow-sm">
                                <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                                <div class="card-body">
                                    <p class="card-text">{{ i.nombre }}</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <!-- <button type="button" class="btn btn-sm btn-outline-secondary">View</button> -->
                                            <a class="btn btn-sm btn-outline-secondary" href="{% url 'productos:detalle' %}">Ver más</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
    {% endblock contenido %}
    

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="es" data-lt-installed="true">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">      
        <title>Login. Acceso al panel de InforMarket</title>
        <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sign-in/">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
            <!-- Favicons -->
        <link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
        <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
        <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
        <link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
        <link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
        <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
        <meta name="theme-color" content="#7952b3">
            <style>
            .bd-placeholder-img {
                font-size: 1.125rem;
                text-anchor: middle;
                -webkit-user-select: none;
                -moz-user-select: none;
                user-select: none;
            }

            @media (min-width: 768px) {
                .bd-placeholder-img-lg {
                font-size: 3.5rem;
                }
            }
            </style>
        <!-- Custom styles for this template -->
        <link href="{% static 'css/login.css' %}" rel="stylesheet">
    </head>
    <body class="text-center">
        <main class="form-signin">
            <form method="POST"> {% csrf_token %}
                <!-- LOGO <img class="mb-4" src="/docs/5.1/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57"> -->
                <h1 class="h3 mb-3 fw-normal">Acceder al Panel. InforMarket</h1>
                {% include "includes/form_errors.html" %}
                <div class="form-floating">
                    <input type="text" class="form-control" id="floatingInput" placeholder="Usuario" autofocus="" name="username">
                    <label for="floatingInput">Usuario</label>
                </div>
                <div class="form-floating">
                    <input type="password" class="form-control" id="floatingPassword" placeholder="Contraseña" name="password">
                    <label for="floatingPassword">Contraseña</label>
                </div>

                <div class="checkbox mb-3">
                    <label>
                        <input type="checkbox" value="remember-me"> Recordar mis datos en este equipo.
                    </label>
                </div>
                <button class="w-100 btn btn-lg btn-primary" type="submit">Ingresar</button>
                <p class="mt-5 mb-3 text-muted"> <a href="{% url 'inicio' %}">Volver al inicio</a></p>
            </form>
        </main>
    </body>
</html>

templates/productos/admin/editar.html
{% extends 'base/base.html' %}
{% block contenido %}
    <div>
        <form method="POST">{% csrf_token %}
            <div class="row" style="padding:10px;">
                {% include "includes/form_errors.html" %}
                {{form.as_p}}
                <div class="col">
                    <button type="submit" class="btn btn-outline-success">Guardar</button>
                    <a href="{% url 'productos:admin_listar' %}" class="btn btn-outline-danger">Cancelar</a>
                </div>
            </div>
        </form>
    </div>
{% endblock contenido %}

templates/productos/admin/eliminar.html
{% extends 'base/base.html' %}
{% block contenido %}
<form method="post">{% csrf_token %}
    <p> "ALERTA!! va a proceder a eliminar este registro: "{{ object }}". ¿Estas seguro? </p>
        <button type="submit" value="Confirm" class="btn btn-danger">Confirmar Borrado</button>
        <a href="{% url 'productos:admin_listar' %}" class="btn btn-secondary">Volver atras</a>
    </form>
{% endblock contenido %}

templates/productos/admin/listar.html
{% extends 'base/base.html' %}

{% block contenido %}
    <div class="row" style="padding:10px;">
        <div class="col">
            <a href="{% url 'productos:admin_nuevo' %}" class="btn btn-outline-success">Nuevo Producto</a>
        </div>
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#id</th>
                <th scope="col">Nombre</th>
                <th scope="col">Precio</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for p in productos %}
                <tr>
                    <th scope="row">{{p.id}}</th>
                    <td>{{p.nombre}}</td>
                    <td>${{p.precio}}</td>
                    <td class="d-grid gap-2 d-md-block">
                        <a href="#" class="btn btn-outline-info">Ver</a>
                        <a href="{% url 'productos:admin_editar' p.id %}" class="btn btn-outline-primary">Editar</a>
                        <a href="{% url 'productos:admin_eliminar' p.id %}" class="btn btn-outline-danger">Eliminar</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock contenido %}

templates/productos/admin/nuevo.html
{% extends 'base/base.html' %}
    {% block contenido %}
        <div>
            <form method="POST">{% csrf_token %}
                <div class="row" style="padding:10px;">
                    {% include "includes/form_errors.html" %}
                    {{form.as_p}}
                    <div class="col">
                        <button type="submit" class="btn btn-outline-success">Guardar</button>
                        <a href="{% url 'productos:admin_listar' %}" class="btn btn-outline-danger">Cancelar</a>
                    </div>
                </div>
            </form>
        </div>
    {% endblock contenido %}

templates/productos/detalle.html
{% extends 'base/base.html' %}

templates/productos/producto_confirm_delete.html
{% extends 'base/base.html' %}
{% block contenido %}
<form method="post">{% csrf_token %}
    <p> "ALERTA!! va a proceder a eliminar este registro: "{{ object }}". ¿Estas seguro? </p>
        <button type="submit" value="Confirm" class="btn btn-danger">Confirmar Borrado</button>
        <a href="{% url 'productos:admin_listar' %}" class="btn btn-secondary">Volver atras</a>
    </form>
{% endblock contenido %}